version: '3.1'

services:
  db:
    image: postgres:11.0
    restart: always
    environment:
        POSTGRES_PASSWORD: example
        POSTGRES_DB: megamerge_development
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL 
